#!/bin/sh
set -e

STORM_USER_HOME=/usr/lib/storm

# /usr/sbin/adduser --system --home=/usr/lib/storm --gecos=Storm --disabled-password --shell=/bin/bash --group storm

# if there is no storm - create one,
# home folder creation is managed by packet
# TODO: questionable if --ingroup parameter should be used instead of --group
if ! getent passwd storm > /dev/null; then

  echo "Creating storm user account and group"
  addgroup --quiet storm

  adduser --system --quiet --home $STORM_USER_HOME --no-create-home \
    --shell /bin/bash --ingroup storm \
    --gecos "Storm distributed realtime computation system" storm
fi

echo "Making sure storm user is unlocked"
if [ -f /etc/shadow ]; then
  usermod -U -e '' storm
else
  usermod -U storm
fi

#DEBHELPER#

[ "$1" = "configure" ] && ldconfig

exit 0
